name: Running static code analysis on branches	

on:	
  # Trigger analysis when pushing in master, develop or pull requests, and when creating
  # a pull request. 
  push:	
    branches:	
      - 'develop'	
      - 'master'	
  pull_request:	
    types: [opened, synchronize, reopened]	

jobs:	
  analyse:	
    runs-on: ubuntu-latest	
    steps:	
    - uses: actions/checkout@v1	
    - uses: actions/setup-node@v1	
      with:	
        node-version: '12.x'	
    - name: Global install	
      run: npm install -g sonarqube-scanner	
    - name: Install	
      run: npm i	
    - name: Sonar analysis	
      env:	
        SONAR_LOGIN: ${{ secrets.SONAR_LOGIN }}	
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}	
      run: npm run sonar